// Code generated by go:generate; DO NOT EDIT.
package enzyme

var DB = map[string]Enzyme{
	"EcoRI": {Name: "EcoRI", Recognition: "G^AATTC", CutIndex: 1},
	"MseI": {Name: "MseI", Recognition: "T^TAA", CutIndex: 1},
	"PstI": {Name: "PstI", Recognition: "CTGCA^G", CutIndex: 5},
}
